name : auto-approve
on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
      - name: Auto approve pull requests
        uses: hmarr/auto-approve-action@v3